# Site settings
title: Alex Barron
slogan: Web Developer, World Traveller
email: alex@alexbarron.xyz
description: > # this means to ignore newlines until "baseurl:"
  Alex Barron is a freelance web developer, backpacker, and blogger of all things tech and travel.
  He is from London but has worked in Melbourne and is currently based somewhere in France.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexbarron.xyz" # the base hostname & protocol for your site
twitter-handle: abarron87
github-handle:  abarron87
linkedin-handle: abarron87
instagram-handle: abarron87
cv-url: https://drive.google.com/file/d/0B0aXeWwu7YD7RTZJZFFQcDUxQ2c/view?usp=sharing

# Build settings
markdown: kramdown
permalink: pretty

exclude: [
  'less',
  'js',
  'node_modules',
  'bower_components',
  'Gruntfile.js',
  'README.md'
]
